name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI  # Add this step
        run: npm install -g @angular/cli

      - name: Build Angular app
        run: ng build --configuration production --base-href /Portfolio/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/port-folio  # Replace with actual project name
